# Generated by Django 3.2.25 on 2024-04-24 03:30

import classification_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationBurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url_before', models.ImageField(blank=True, null=True, upload_to=classification_model.models.upload_to)),
                ('img_url_after', models.ImageField(blank=True, null=True, upload_to=classification_model.models.upload_to)),
                ('result', models.CharField(max_length=80)),
            ],
        ),
    ]
