# Generated by Django 3.2.25 on 2024-04-30 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classified_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteers_evaluation_score', models.IntegerField(null=True)),
                ('number_of_evalutors_per_image', models.IntegerField(null=True)),
                ('image_with_model_classification', models.ImageField(upload_to='')),
                ('confidence_score', models.IntegerField(null=True)),
                ('burn_degree', models.IntegerField(null=True)),
                ('image_width', models.IntegerField(null=True)),
                ('image_height', models.IntegerField(null=True)),
                ('image_cordinate_x', models.IntegerField(null=True)),
                ('image_cordinate_y', models.IntegerField(null=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.image')),
            ],
        ),
    ]
