# Generated by Django 3.2.25 on 2024-05-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified_image',
            name='confidence_score',
            field=models.FloatField(null=True),
        ),
    ]
