# Generated by Django 3.2.25 on 2024-05-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_image', '0002_alter_classified_image_confidence_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified_image',
            name='burn_degree',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
