# Generated by Django 3.2.25 on 2024-05-09 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_image_user'),
        ('classified_image', '0003_alter_classified_image_burn_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified_image',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_image', to='image.image'),
        ),
    ]
